project:
  type: website
  resources:
  - "static/*"
  - "media/*"
  # pre-render: 
    # - pre-render/timeline-main.ts
    # - bundle src/timeline-runtime.ts  static/timeline-runtime.js
    # - deno run --check -A pre-render/test.ts

bibliography: references.bib

website:
  title: "Essentials of Health Informatics"
  site-url: "https://essential-health-informatics.com/"
  navbar:
    left:
      - href: /chapters/index.html
        text: Chapters
      - href: /chapters/timeline/england/index.html
        text: UK timeline
  favicon: media/eohi-logo.png

metadata-files:
  - sidebar.yml


format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
