project:
  type: website
  resources:
  - "static/*"
  - "media/*"

bibliography: references.bib

website:
  title: "Essentials of Health Informatics"
  site-url: "https://essential-health-informatics.com/"
  navbar:
    left:
      - href: /chapters/index.html
        text: Chapters
      - href: /chapters/timeline/uk.html
        text: UK timeline
  favicon: media/eohi-logo.png
  sidebar:
    contents: chapters



format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
