project:
  type: website
  resources:
  - "static/*"
  - "media/*"
  # post-render:
  #   - npm exec ts-node utils/banners.ts

bibliography: references.bib

website:
  title: "Essentials of Health Informatics"
  site-url: "https://essential-health-informatics.com/"
  navbar:
    left:
      - href: /chapters/index.html
        text: Chapters
      - href: /chapters/7-history-of-digital-health-across-the-globe/1-england/index.html
        text: UK timeline
  favicon: media/eohi-logo.png

metadata-files:
  - sidebar.yml


format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
