on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  cicd_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: run CI CD tasks
        run: bash ci-cd.sh
      
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}